server:
  port: 8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: somuca
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/somuca?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
management:
  endpoints:
    web:
      exposure:
        include:
        - health
  endpoint:
    health:
      probes:
        enabled: true
        
